/*
 *      CENTRO FEDERAL DE EDUCAÇÃO TECNOLÓGICA DE MINAS GERAIS
 * ENGENHARIA DE COMPUTAÇÃO - LABORATORIO DE LINGUAGEM DE PROGRAMAÇÃO
 * 
 *                    ANTONIO SOUSA E GABRIEL NEGREIROS
 */

package GUI;

import Console.arquivo;
import Serviços.ItemPedido;
import Serviços.Servico;
import Serviços.ServicoOrcado;
import Usuario.Usuario;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;

public class GUI_FazerPedido extends javax.swing.JFrame {
    static int pedidos = 1;
    private ArrayList<ServicoOrcado> Servicos;
    private ArrayList<ItemPedido> Pedidos;
    private Usuario cliente;
    private ItemPedido ItemAtual;
    int itens = 0;
   
    /**
     * Creates new form GUI_ListaServicosAtivados
     */
    public GUI_FazerPedido(Usuario cliente) throws FileNotFoundException, IOException {
        initComponents();
        
        this.cliente = cliente;
        // Centraliza o JFrame na tela
        this.setLocationRelativeTo(null);
        
        jComboBox_Servicos.removeAllItems();
                
        arquivo x = new arquivo();
        Servicos = x.getServicosOrcados();
        Pedidos = x.getPedidos();
        
        if(Pedidos.size()>0 && pedidos==1){
            pedidos = Integer.parseInt(Pedidos.get(Pedidos.size()-1).getPedido())+1;
        }
        //pedidos = Integer.parseInt("1");
        //System.out.println(Pedidos.get(Pedidos.size()-1).getPedido());
        
        for (Iterator iterator = Servicos.iterator(); iterator.hasNext(); ) {  
            ServicoOrcado lido = (ServicoOrcado) iterator.next();
           
            jComboBox_Servicos.addItem(lido.getServico().getTipoServico());
        }
        
        this.jTextField_Observacoes.setEditable(false);
        this.jTextField_Observacoes.setEnabled(false);
        
        this.jTextField_Preco.setEditable(false);
        this.jTextField_Preco.setEnabled(false);
        
        this.jTextField_Profissional.setEditable(false);
        this.jTextField_Profissional.setEnabled(false);
        
        this.jTextField_Pedido.setEditable(false);
        this.jTextField_Pedido.setEnabled(false);
        
        this.jTextField_NItens.setEditable(false);
        this.jTextField_NItens.setEnabled(false);
        
        this.jButton_EfetuarPedido.setVisible(false);
        
        this.jTextField_Pedido.setText(Integer.toString(pedidos));
        this.jTextField_NItens.setText(Integer.toString(itens));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jComboBox_Servicos = new javax.swing.JComboBox<>();
        jTextField_Observacoes = new javax.swing.JTextField();
        jButton_Cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Preco = new javax.swing.JTextField();
        jTextField_Profissional = new javax.swing.JTextField();
        jLabel_Profissional = new javax.swing.JLabel();
        jButton_EfetuarPedido = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField_Pedido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_NItens = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Confira abaixo os serviços disponíveis:");

        jComboBox_Servicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Servicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ServicosActionPerformed(evt);
            }
        });

        jTextField_Observacoes.setText("Observações");
        jTextField_Observacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ObservacoesActionPerformed(evt);
            }
        });

        jButton_Cancelar.setText("Cancelar");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Serviço:");

        jLabel3.setText("Observação:");

        jLabel4.setText("Preço:");

        jTextField_Preco.setText("Preço Solicitado");
        jTextField_Preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PrecoActionPerformed(evt);
            }
        });

        jTextField_Profissional.setText("Profissional");
        jTextField_Profissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ProfissionalActionPerformed(evt);
            }
        });

        jLabel_Profissional.setText("Profissional");

        jButton_EfetuarPedido.setText("Efetuar Pedido");
        jButton_EfetuarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EfetuarPedidoActionPerformed(evt);
            }
        });

        jButton1.setText("Adicionar Esse Serviço ao Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField_Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PedidoActionPerformed(evt);
            }
        });

        jLabel5.setText("Pedido Nº:");

        jLabel6.setText("Nºs de Itens no pedido:");

        jTextField_NItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NItensActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_EfetuarPedido))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField_Profissional, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                        .addComponent(jLabel_Profissional, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox_Servicos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_Observacoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                        .addComponent(jTextField_Preco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_NItens, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_Servicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(jTextField_Observacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(jTextField_Preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Profissional)
                .addGap(2, 2, 2)
                .addComponent(jTextField_Profissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_NItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cancelar)
                    .addComponent(jButton_EfetuarPedido))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_ServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ServicosActionPerformed
        // TODO add your handling code here:
        int index_selecionado = jComboBox_Servicos.getSelectedIndex();
        
        if(index_selecionado>=0){
            ServicoOrcado selecionado = Servicos.get(index_selecionado);
            jTextField_Observacoes.setText(selecionado.getServico().getObservacaoServico());
            jTextField_Preco.setText(selecionado.getPreco());
            jTextField_Profissional.setText(selecionado.getProfissional());
            
            ItemAtual = new ItemPedido(selecionado, cliente.getUsuario(), Integer.toString(pedidos), "0");
            //System.out.println(selecionado.getTipoServico());

        }
    }//GEN-LAST:event_jComboBox_ServicosActionPerformed

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    private void jTextField_PrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PrecoActionPerformed

    private void jTextField_ObservacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ObservacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ObservacoesActionPerformed

    private void jTextField_ProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ProfissionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ProfissionalActionPerformed

    private void jButton_EfetuarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EfetuarPedidoActionPerformed
        try {
            // TODO add your handling code here:
            arquivo x = new arquivo();
            x.setPedidos(Pedidos);
            pedidos++;
            this.dispose();
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GUI_FazerPedido.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GUI_FazerPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton_EfetuarPedidoActionPerformed

    private void jTextField_PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PedidoActionPerformed

    private void jTextField_NItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NItensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NItensActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Pedidos.add(ItemAtual);
        itens++;
        this.jTextField_NItens.setText(Integer.toString(itens));
        this.jButton_EfetuarPedido.setVisible(true);
        new GUI_ItemInserido().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_EfetuarPedido;
    private javax.swing.JComboBox<String> jComboBox_Servicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_Profissional;
    private javax.swing.JTextField jTextField_NItens;
    private javax.swing.JTextField jTextField_Observacoes;
    private javax.swing.JTextField jTextField_Pedido;
    private javax.swing.JTextField jTextField_Preco;
    private javax.swing.JTextField jTextField_Profissional;
    // End of variables declaration//GEN-END:variables
}
