/*
 *      CENTRO FEDERAL DE EDUCAÇÃO TECNOLÓGICA DE MINAS GERAIS
 * ENGENHARIA DE COMPUTAÇÃO - LABORATORIO DE LINGUAGEM DE PROGRAMAÇÃO
 * 
 *                    ANTONIO SOUSA E GABRIEL NEGREIROS
 */

package GUI;

import Console.arquivo;
import Usuario.*;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.layout.Border;
import javax.swing.SwingConstants;
import sun.swing.SwingAccessor;

/**
 *
 * @author Aluno
 */
public class GUI_TestaLogin extends javax.swing.JFrame {

    private ArrayList<Usuario> Usuarios;
    
    BufferedReader buffReadUsers;
    Usuario logador;
    String tipo_usuario;
    /**
     * Creates new form GUI_TestaLogin
     * @param logador
     * @throws java.io.FileNotFoundException
     */
    public GUI_TestaLogin(Usuario logador) throws FileNotFoundException, IOException {
        //this.buffReadUsers = new BufferedReader(new FileReader("usuarios.txt"));
     
        this.logador = new Usuario(logador.getUsuario(), logador.getSenha());
        //this.logador = logador;
        
        initComponents();
        
        // Centraliza o JFrame na tela
        this.setLocationRelativeTo(null);
        
        // Configura botoes
        this.jButton_Entrar.setVisible(false);  
        this.jButton_Voltar.setVisible(false);
        
        testaLogin();
    }
    
    public void testaLogin() throws IOException{
        
        jLabel1.setLocation((this.getWidth()-jLabel1.getWidth())/2,200);        
    
        arquivo x = new arquivo();
        Usuarios = x.getUsuarios();
        
        for (Iterator iterator = Usuarios.iterator(); iterator.hasNext(); ) {  
            Usuario lido = (Usuario) iterator.next();
            
            if(lido.getUsuario()!= null && this.logador.getUsuario().equals(lido.getUsuario()) && this.logador.getSenha().equals(lido.getSenha())){
                tipo_usuario = lido.getClass().getSimpleName();
                jButton_Voltar.setVisible(false);
                jLabel1.setText("Login efetuado com sucesso!");
                jLabel1.setVisible(true);
                jButton_Entrar.setVisible(true);
                return;
            }
        }
        
        jButton_Entrar.setVisible(false);
        jLabel1.setText("         Login falho! Confira seu login e senha e tente novamente.");
        jLabel1.setVisible(true);
        jButton_Voltar.setVisible(true);
        
        jLabel1.setVerticalAlignment(SwingConstants.CENTER);
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton_Voltar = new javax.swing.JButton();
        jButton_Entrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("xxxxxxxxxxx");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton_Voltar.setText("Voltar");
        jButton_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VoltarActionPerformed(evt);
            }
        });

        jButton_Entrar.setText("Entrar");
        jButton_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Voltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addComponent(jButton_Entrar)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Voltar)
                    .addComponent(jButton_Entrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VoltarActionPerformed
        new GUI_Login(logador).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_VoltarActionPerformed

    private void jButton_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EntrarActionPerformed
        switch (tipo_usuario) {
            case "Administrador":
                new GUI_MenuPrincipal_Admin(logador).setVisible(true);
                break;
            case "Cliente":
                new GUI_MenuPrincipal_Cliente(logador).setVisible(true);
                break;
            case "Profissional":
                new GUI_MenuPrincipal_Profissional( logador).setVisible(true);
                break;
            default:
                break;
        }
        this.dispose();
    }//GEN-LAST:event_jButton_EntrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Entrar;
    private javax.swing.JButton jButton_Voltar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
