/*
 *      CENTRO FEDERAL DE EDUCAÇÃO TECNOLÓGICA DE MINAS GERAIS
 * ENGENHARIA DE COMPUTAÇÃO - LABORATORIO DE LINGUAGEM DE PROGRAMAÇÃO
 * 
 *                    ANTONIO SOUSA E GABRIEL NEGREIROS
 */

package GUI;

import Usuario.Profissional;
import Usuario.Usuario;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Negreiros
 */
public class GUI_MenuPrincipal_Profissional extends javax.swing.JFrame {

    private Usuario profissional;
    /**
     * Creates new form GUI_MenuPrincipal_Profissional
     */
    public GUI_MenuPrincipal_Profissional(Usuario profissional) {
        initComponents();
        
        // Centraliza o JFrame na tela
        this.setLocationRelativeTo(null);
        this.profissional = profissional;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton_Cadastro_servico = new javax.swing.JButton();
        jButton_ServicosAtivados = new javax.swing.JButton();
        jButton_OrcarServico = new javax.swing.JButton();
        jButton_ServicosOrcados = new javax.swing.JButton();
        jButton_VerPedidos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MENU PRINCIPAL DO PROFISSIONAL");

        jButton_Cadastro_servico.setText("Cadastrar Serviço");
        jButton_Cadastro_servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cadastro_servicoActionPerformed(evt);
            }
        });

        jButton_ServicosAtivados.setText("Serviços Ativados");
        jButton_ServicosAtivados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ServicosAtivadosActionPerformed(evt);
            }
        });

        jButton_OrcarServico.setText("Orçar Serviço");
        jButton_OrcarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OrcarServicoActionPerformed(evt);
            }
        });

        jButton_ServicosOrcados.setText("Serviços Orçados");
        jButton_ServicosOrcados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ServicosOrcadosActionPerformed(evt);
            }
        });

        jButton_VerPedidos.setText("Ver Pedidos");
        jButton_VerPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VerPedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel1)
                .addContainerGap(229, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(506, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton_VerPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton_ServicosOrcados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_OrcarServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_ServicosAtivados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Cadastro_servico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Cadastro_servico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_ServicosAtivados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_OrcarServico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_ServicosOrcados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_VerPedidos)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Cadastro_servicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cadastro_servicoActionPerformed
        new GUI_CadastraServico().setVisible(true);
    }//GEN-LAST:event_jButton_Cadastro_servicoActionPerformed

    private void jButton_ServicosAtivadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ServicosAtivadosActionPerformed
        try {
            // TODO add your handling code here:
            new GUI_ListaServicosAtivados().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(GUI_MenuPrincipal_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_ServicosAtivadosActionPerformed

    private void jButton_OrcarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OrcarServicoActionPerformed
        try {
            new GUI_OrcarServico(profissional).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(GUI_MenuPrincipal_Profissional.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_OrcarServicoActionPerformed

    private void jButton_ServicosOrcadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ServicosOrcadosActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            new GUI_ListaServicosOrcados(profissional).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(GUI_MenuPrincipal_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_ServicosOrcadosActionPerformed

    private void jButton_VerPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VerPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_VerPedidosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cadastro_servico;
    private javax.swing.JButton jButton_OrcarServico;
    private javax.swing.JButton jButton_ServicosAtivados;
    private javax.swing.JButton jButton_ServicosOrcados;
    private javax.swing.JButton jButton_VerPedidos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
