/*
 *      CENTRO FEDERAL DE EDUCAÇÃO TECNOLÓGICA DE MINAS GERAIS
 * ENGENHARIA DE COMPUTAÇÃO - LABORATORIO DE LINGUAGEM DE PROGRAMAÇÃO
 * 
 *                    ANTONIO SOUSA E GABRIEL NEGREIROS
 */

package GUI;

import Console.arquivo;
import Serviços.Servico;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

public class GUI_CadastraServico extends javax.swing.JFrame {

     private ArrayList<Servico> Servicos;
    /**
     * Creates new form GUI_CadastraServico
     */
    public GUI_CadastraServico() {
        initComponents();
        
        // Centraliza o JFrame na tela
        this.setLocationRelativeTo(null);
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton_VerificaServico = new javax.swing.JButton();
        jTextField_NomeServico = new javax.swing.JTextField();
        jTextField_ObservacaoServico = new javax.swing.JTextField();
        jButton_Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Escreva o nome do serviço e uma observação sobre o serviço que deseja cadastrar");

        jButton_VerificaServico.setText("Criar serviço");
        jButton_VerificaServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VerificaServicoActionPerformed(evt);
            }
        });

        jTextField_NomeServico.setText("Nome do Serviço");
        jTextField_NomeServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NomeServicoActionPerformed(evt);
            }
        });

        jTextField_ObservacaoServico.setText("Observação do serviço que deseja...");
        jTextField_ObservacaoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ObservacaoServicoActionPerformed(evt);
            }
        });

        jButton_Voltar.setText("Voltar");
        jButton_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Voltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_VerificaServico)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_NomeServico, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                    .addComponent(jTextField_ObservacaoServico))
                .addGap(0, 86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addComponent(jTextField_NomeServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField_ObservacaoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_VerificaServico)
                    .addComponent(jButton_Voltar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_VerificaServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VerificaServicoActionPerformed
       
        try {
            
            arquivo x = new arquivo();
            Servicos = x.getServicos();
            
            Servico Inserir = new Servico(jTextField_NomeServico.getText(),jTextField_ObservacaoServico.getText());
            Servicos.add(Inserir);
            
            x.setServicos(Servicos);

            this.dispose();
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GUI_CadastraServico.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
             Logger.getLogger(GUI_CadastraServico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_VerificaServicoActionPerformed

    private void jTextField_NomeServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NomeServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NomeServicoActionPerformed

    private void jTextField_ObservacaoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ObservacaoServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ObservacaoServicoActionPerformed

    private void jButton_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VoltarActionPerformed
        // TODO add your handling code here:
        this.dispose(); //Fecahr aba
    }//GEN-LAST:event_jButton_VoltarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_VerificaServico;
    private javax.swing.JButton jButton_Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField_NomeServico;
    private javax.swing.JTextField jTextField_ObservacaoServico;
    // End of variables declaration//GEN-END:variables
}
